# Generated by Django 4.1.4 on 2023-02-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_offers_end_date_offers_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
